<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>smart-call</artifactId>
        <groupId>com.qidiangk.smart</groupId>
        <version>1.0.1</version>
    </parent>

    <artifactId>smart-boot</artifactId>

    <dependencies>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-auth</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-resource</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-system</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-user</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-log</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-aster</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.qidiangk.smart</groupId>
            <artifactId>smart-maxkb</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-nacos</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <build>
        <finalName>smart-boot</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                    <mainClass>com.qidiangk.smart.boot.BootStartApplication</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <container>
                        <workingDirectory>/smart/boot</workingDirectory>
                        <mainClass>com.qidiangk.smart.boot.BootStartApplication</mainClass>
                        <ports>
                            <port>9999</port>
                        </ports>
                    </container>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <!-- 编译 src/main/java 目录下的 mapper 文件 -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <!-- ......用于扫描 dao 文件下的mapper 文件................. end -->
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
    </build>
</project>