spring:
  main:
    ## @FeignClient(value = "服务名") 设置可以有多个类存在相同的FeignClient 中的value值
    allow-bean-definition-overriding: true
#  todo 暂时没有实现调用根目录配置文件方式，不能放掉注释，会导致项目的配置文件优先级改变
#  config:
#    import:
#      - "optional:classpath:./bootstrap.yml"
#      - "optional:file:./conf/bootstrap.yml"
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false