server:
  port: 18000

spring:
  config:
    import:
      - optional:nacos:smart.yml
      - optional:nacos:smart-dev.yml
      - optional:nacos:smart-doc.yml
      - optional:nacos:smart-doc-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false   # 默认为 false，设为 true 后，缺失的配置会导致启动失败
        namespace: ab6f9a98-fcdf-400c-b3d6-3f1d3e110a1a
      discovery:
        namespace: ab6f9a98-fcdf-400c-b3d6-3f1d3e110a1a
knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 日志模块
        uri: localhost:9000
        location: /smart-log/v3/api-docs
      - name: 系统管理
        uri: localhost:9000
        location: /smart-system/v3/api-docs
      - name: 授权模块
        uri: localhost:9000
        location: /smart-auth/v3/api-docs
      - name: 用户模块
        uri: localhost:9000
        location: /smart-user/v3/api-docs
      - name: 文件模块
        uri: localhost:9000
        location: /smart-file/v3/api-docs