server:
  port: 9004

spring:
  config:
    import:
      - nacos:jpower.yml
      - nacos:jpower-dev.yml
      - nacos:jpower-resource.yml
  cloud:
    nacos:
      server-addr: 8.130.172.218:8848
      config:
        import-check:
          enabled: false   # 默认为 false，设为 true 后，缺失的配置会导致启动失败


fdfs:
  # 链接超时
  connect-timeout: 1800
  # 读取时间
  so-timeout: 1800
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 219.148.186.235:22122

jpower:
  file:
    server:
      # 服务器文件外链访问地址
      domain: http://xxx.xxx.xxx/file
      # 服务器文件保存路径
      path: ./file
    fastDfs:
      # FastDfs文件外链访问地址
      domain: http://xxx.xxx.xxx