spring:
  main:
    ## @FeignClient(value = "服务名") 设置可以有多个类存在相同的FeignClient 中的value值
    allow-bean-definition-overriding: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true