<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.0</version>
    </parent>
    
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-upms</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>jpower-system</module>
        <module>jpower-user</module>
        <module>jpower-resource</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-boot</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-swagger</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-redis</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-log</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-common</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-deploy</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-dbs</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <!-- 编译 src/main/java 目录下的 mapper 文件 -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <!-- ......用于扫描 dao 文件下的mapper 文件................. end -->
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <!-- 编译 根 目录下的 bootstrap-jpower.yml 文件 -->
            <resource>
                <directory>${maven.multiModuleProjectDirectory}/config</directory>
                <filtering>false</filtering>
                <includes>
                    <include>bootstrap-jpower.yml</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>