<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>top.jpower</groupId>
    <artifactId>jpower</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <name>JPower</name>
    <description>
        JPower微服务快速开发平台
    </description>
    <url>https://gitee.com/gdzWork/JPower</url>

    <developers>
        <developer>
            <id>mr.g</id>
            <name>Tzu-Ding Goo</name>
            <email>ding931226@yeah.net</email>
            <organization>JPower</organization>
            <organizationUrl>https://gitee.com/gdzWork</organizationUrl>
            <timezone>+8</timezone>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <connection>https://gitee.com/gdzWork/JPower.git</connection>
        <developerConnection>https://gitee.com/gdzWork</developerConnection>
        <url>https://gitee.com/gdzWork/JPower.git</url>
    </scm>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <top.jpower.version>3.0.0</top.jpower.version>

        <spring-boot.version>3.5.8</spring-boot.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <spring-alibaba.version>2025.0.0.0</spring-alibaba.version>
        <fastjson.version>2.0.58</fastjson.version>
        <poi.version>3.17</poi.version>
        <jsqlparser.version>5.3</jsqlparser.version>
        <hutool.version>5.8.42</hutool.version>
        <redisson.version>3.52.0</redisson.version>
        <druid-spring.version>1.2.27</druid-spring.version>
        <logstash.version>9.0</logstash.version>
        <skywalking.version>9.5.0</skywalking.version>
        <easy-captcha.version>1.6.2</easy-captcha.version>
        <fastdfs.version>1.27.2</fastdfs.version>
        <aliyun.sms.version>4.3.1</aliyun.sms.version> <!--2.0.24-->
        <aliyun.oss.version>3.18.3</aliyun.oss.version><!--3.17.4-->
        <qiniu.oss.version>7.19.0</qiniu.oss.version><!--7.15.0-->

        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <maven-resources.version>3.4.0</maven-resources.version><!--3.3.1-->
        <maven-gpg.version>3.2.8</maven-gpg.version><!--3.1.0-->
        <dockerfile-maven-plugin.version>1.4.13</dockerfile-maven-plugin.version>

        <docker.image.prefix>jpower</docker.image.prefix>
        <docker.registry>118.31.115.232:5000</docker.registry>

        <!-- ****************** 升级中 ********************** -->


        <pagehelper-spring.version>1.4.1</pagehelper-spring.version>
        <mybatis-plus.version>3.5.5</mybatis-plus.version>
        <jwt.version>0.6.0</jwt.version>
        <knife4j.version>4.4.0</knife4j.version>
        <swagger-annotations.version>1.6.2</swagger-annotations.version>
        <spring-boot-admin.version>2.7.15</spring-boot-admin.version>


    </properties>

    <modules>
        <module>jpower-auth</module>
        <module>jpower-core</module>
        <module>jpower-gateway</module>
        <module>jpower-api</module>
        <module>jpower-upms</module>
        <module>jpower-ops</module>
        <module>jpower-common</module>
        <module>jpower-boot</module>
    </modules>

    <dependencies>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>

            <!-- spring boot 依赖 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- spring cloud 依赖 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- spring cloud alibaba 依赖 -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- knife4j -->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-dependencies</artifactId>
                <version>${knife4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 排除knife4j中的hutool -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <!-- spring-boot-admin -->
            <dependency>
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-starter-server</artifactId>
                <version>${spring-boot-admin.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>release</id>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-deploy-plugin</artifactId>
                    </plugin>
                    <!-- GPG -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>jpower-central</publishingServerId>
                            <autoPublish>true</autoPublish>
                            <waitUntil>published</waitUntil>
                            <excludeArtifacts>
                                <excludeArtifact>jpower-api</excludeArtifact>
                                <excludeArtifact>jpower-auth</excludeArtifact>
                                <excludeArtifact>jpower-boot</excludeArtifact>
                                <excludeArtifact>jpower-common</excludeArtifact>
                                <excludeArtifact>jpower-gateway</excludeArtifact>
                                <excludeArtifact>jpower-ops</excludeArtifact>
                                <excludeArtifact>jpower-upms</excludeArtifact>
                                <excludeArtifact>jpower-admin</excludeArtifact>
                                <excludeArtifact>jpower-doc</excludeArtifact>
                                <excludeArtifact>jpower-log</excludeArtifact>
                                <excludeArtifact>jpower-resource-api</excludeArtifact>
                                <excludeArtifact>jpower-system-api</excludeArtifact>
                                <excludeArtifact>jpower-user-api</excludeArtifact>
                                <excludeArtifact>jpower-resource</excludeArtifact>
                                <excludeArtifact>jpower-system</excludeArtifact>
                                <excludeArtifact>jpower-user</excludeArtifact>
                            </excludeArtifacts>
                        </configuration>
                    </plugin>
                </plugins>
            </build>

        </profile>
    </profiles>

    <build>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <configuration>
                        <classifier>exec</classifier>
                        <!--生成可执行jar的名称-->
                        <finalName>${project.build.finalName}</finalName>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- dockerfile -->
                <plugin>
                    <groupId>com.spotify</groupId>
                    <artifactId>dockerfile-maven-plugin</artifactId>
                    <version>${dockerfile-maven-plugin.version}</version>
                    <configuration>
                        <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
                        <repository>${docker.registry}/${docker.image.prefix}/${project.build.finalName}</repository>
                        <tag>${project.version}</tag>
                        <buildArgs>
                            <JAR_FILE>target/${project.build.finalName}-exec.jar</JAR_FILE>
                        </buildArgs>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </path>
                    </annotationProcessorPaths>
                    <debug>false</debug>
                </configuration>
            </plugin>

        </plugins>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
    </build>

    <!-- 指定 Maven 源 -->
    <repositories>
        <repository>
            <id>aliyunmaven</id>
            <name>aliyun</name>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>

        <repository>
            <id>huaweicloud</id>
            <name>huawei</name>
            <url>https://mirrors.huaweicloud.com/repository/maven/</url>
        </repository>

        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

</project>