<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>top.jpower</groupId>
        <artifactId>jpower</artifactId>
        <version>3.0.1</version>
    </parent>

    <modules>
        <module>jpower-core-auth</module>
        <module>jpower-core-deploy</module>
        <module>jpower-core-nacos</module>
        <module>jpower-core-redis</module>
        <module>jpower-core-swagger</module>
        <module>jpower-core-util</module>
        <module>jpower-core-dbs</module>
        <module>jpower-core-seata</module>
        <module>jpower-core-exception</module>
        <module>jpower-core-boot</module>
        <module>jpower-core-feign</module>
        <module>jpower-core-log</module>
        <module>jpower-core-ai</module>
        <module>jpower-core-asterisk</module>
    </modules>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-core</artifactId>
    <name>JPower Core</name>
    <packaging>pom</packaging>

    <dependencies>

        <!--生成自定义配置属性生成元数据文件-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-aop</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.retry</groupId>-->
<!--            <artifactId>spring-retry</artifactId>-->
<!--        </dependency>-->

    </dependencies>

    <build>
        <plugins>
            <!-- Source -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-deploy-plugin</artifactId>
                    </plugin>
                    <!-- Javadoc -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.12.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <failOnError>false</failOnError>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>
</project>
