<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower-core</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.1</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-core-exception</artifactId>
    <name>JPower Core Exception</name>
    <packaging>jar</packaging>
    <description>
        JPower 异常捕获、日志记录
    </description>

    <dependencies>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-deploy</artifactId>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-feign</artifactId>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-deploy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>