server:
  port: 18000

spring:
  config:
    import:
      - nacos:jpower.yml
      - nacos:jpower-dev.yml
      - nacos:jpower-doc.yml
      - nacos:jpower-doc-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false   # 默认为 false，设为 true 后，缺失的配置会导致启动失败

knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 日志模块
        uri: localhost:9000
        location: /jpower-log/v3/api-docs
      - name: 系统管理
        uri: localhost:9000
        location: /jpower-system/v3/api-docs
      - name: 授权模块
        uri: localhost:9000
        location: /jpower-auth/v3/api-docs
      - name: 用户模块
        uri: localhost:9000
        location: /jpower-user/v3/api-docs
      - name: 文件模块
        uri: localhost:9000
        location: /jpower-file/v3/api-docs