server:
  port: 9002

spring:
  config:
    import:
      - nacos:jpower.yml
      - nacos:jpower-dev.yml
      - nacos:jpower-system.yml
      - nacos:jpower-system-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false   # 默认为 false，设为 true 后，缺失的配置会导致启动失败