#通用配置
servlet:
  multipart:
    enabled: true
    #单个数据的大小
    max-file-size: 10MB
    #总数据的大小
    max-request-size: 20MB
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    # 线程配置
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 400

spring:
  cloud:
    sentinel:
      eager: true
      log:
        dir: ./logs/sentinel
  security:
    user:
      name: "admin"
      password: "admin"

#feign配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

management:
  endpoint:
    shutdown:
      #开启端点
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #开启所有接口
        include: "*"

#knife4j配置
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: false
    username: jpower
    password: jpower
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://localhost
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
    enableVersion: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright © 2021 JPower All Rights Reserved

#swagger公共信息
swagger:
  title: JPower 接口文档系统
  description: JPower 接口文档系统
  version: 2.0.2
  license: Powered By JPower
  license-url: https://gitee.com/gdzWork/JPower
  terms-of-service-url: http://jpower.top
  contact:
    name: mr.g
    email: ding931226@yeah.net
    url: https://gitee.com/gdzWork

jpower:
  #文件存储地址（自己改成自己文件存储路径即可，如果docker部署要记得修改docker-compose.yml的映射路径）
  fileParentPath: /root/file
#  seata:
##   是否启用分布式事务（默认不开启）
#    enabled: false
#  tenant:
##    是否启用多租户模式
#    enable: true
##   多租户字段
#    column: tenant_code
##   不进行多租户过滤的表
#    excludeTables:
#      - tb_core_table
#  xss:
#    #是否开启富文本过滤(如果开启，content参数名和以WithHtml结尾得参数名将不进行XSS过滤，默认位关闭)
#    isIncludeRichText: false
#    #XSS不过滤得接口路径，支持通配符模式
#    excludes:
#      - /html/**
#  auth:
#    skipUrl:
#      - /auth/**
#      - /core/user/downloadTemplate
#    client:
##开启需要校验的客户端，值写数据库的clientCode即可
#      - code: admin
##需要客户端校验的URL
#        path:
#          - /core/user/**
##鉴权需要过滤的白名单地址
#    whileIp:
#      - 192.168.1.2
#      - 0:0:0:0:0:0:0:1