#通用开发环境配置

#redis配置
spring:
  redis:
    ##redis 单机环境配置
    host: 192.168.128.100
    port: 6379
    password: Wlcb20200515
    database: 99
    timeout: 5000
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000

jpower:
  prod:
    nacos:
      #      注册中心地址
      server-addr: 219.148.186.226:8848
      #注册中心命名空间   （可以为空但不能删掉这块配置）
      namespace:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.3.189.156:18992/csrrg?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: root
    redis:
      host: 192.168.128.100
      password: Wlcb20200515
      port: 6379
      database: 0