server:
  port: 9003

spring:
  config:
    import:
      - optional:nacos:jpower.yml
      - optional:nacos:jpower-dev.yml
      - optional:nacos:jpower-user.yml
      - optional:nacos:jpower-user-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        import-check:
          enabled: false