<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.0</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-gateway</artifactId>

    <dependencies>
        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-deploy</artifactId>
            <version>${top.jpower.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-redis</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-log</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-common</artifactId>
            <version>${top.jpower.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-dbs</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-boot</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-exception</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

        <!--替换loadbalancer默认缓存实现-->
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>jpower-gateway</finalName>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>

        </plugins>

        <resources>
            <!-- 编译 src/main/java 目录下的 mapper 文件 -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <!-- ......用于扫描 dao 文件下的mapper 文件................. end -->
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <!-- 编译 根 目录下的 bootstrap-jpower.yml 文件 -->
            <resource>
                <directory>${maven.multiModuleProjectDirectory}/config</directory>
                <filtering>false</filtering>
                <includes>
                    <include>bootstrap-jpower.yml</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>