version: '3'
services:
  nacos:
    image: "nacos/nacos-server:1.3.2"
    hostname: "nacos-standalone"
    privileged: true
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
#      如不需要数据库做数据持久化配置删掉下面得环境变量即可
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.128.97
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=Wlcb@20200515
    volumes:
      - /docker/nacos/standalone-logs/:/home/nacos/logs
      - /docker/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.50

  sentinel:
    image: "jpowerplus/sentinel-dashboard:1.8.0"
    hostname: "sentinel-standalone"
    privileged: true
    volumes:
      - /docker/sentinel/logs/:/root/logs/csp/
    ports:
      - 8858:8858
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.51

  jpower-gateway:
    image: "219.148.186.235:8861/jpower/gateway-server:1.0.1-SNAPSHOT"
    privileged: true
    volumes:
#      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /root/config/skywalking/skywalking-apm/agent/:/root/config/skywalking/skywalking-apm/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/root/config/skywalking/skywalking-apm/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=219.148.186.214:11800
    ports:
      - 800:80
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.25

  jpower-auth:
    image: "219.148.186.235:8861/jpower/auth-server:1.0.1-SNAPSHOT"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /root/config/skywalking/skywalking-apm/agent/:/root/config/skywalking/skywalking-apm/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/root/config/skywalking/skywalking-apm/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=219.148.186.214:11800
    restart: always
    networks:
      - jpower_net

  jpower-user:
    image: "219.148.186.235:8861/jpower/user-server:1.0.1-SNAPSHOT"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /root/config/skywalking/skywalking-apm/agent/:/root/config/skywalking/skywalking-apm/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/root/config/skywalking/skywalking-apm/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=219.148.186.214:11800
    restart: always
    networks:
      - jpower_net

  jpower-system:
    image: "219.148.186.235:8861/jpower/system-server:1.0.1-SNAPSHOT"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /root/config/skywalking/skywalking-apm/agent/:/root/config/skywalking/skywalking-apm/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/root/config/skywalking/skywalking-apm/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=219.148.186.214:11800
    restart: always
    networks:
      - jpower_net

  jpower-file:
    image: "219.148.186.235:8861/jpower/file-server:1.0.1-SNAPSHOT"
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /root/config/skywalking/skywalking-apm/agent/:/root/config/skywalking/skywalking-apm/agent/
      - /docker/file/:/root/file
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/root/config/skywalking/skywalking-apm/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=219.148.186.214:11800
    privileged: true
    restart: always
    networks:
      - jpower_net

networks:
  jpower_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24