<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower-core</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.0</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-core-feign</artifactId>
    <name>JPower Core Feign</name>
    <description>
        JPower Feign服务
    </description>

    <dependencies>

        <!--servlet-api-->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-auth</artifactId>
            <version>${top.jpower.version}</version>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-util</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>top.jpower</groupId>
                    <artifactId>jpower-core-deploy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-util</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-deploy</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <!-- okhttp 扩展 -->
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
        </dependency>
        <!-- LB 扩展 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <!--caffeine 替换LB 默认缓存实现-->
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>

    </dependencies>
</project>