<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower-core</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.1</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-core-nacos</artifactId>
    <name>JPower Core Nacos</name>
    <packaging>jar</packaging>
    <description>
        JPower Nacos注册中心以及配置中心
    </description>

    <dependencies>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-deploy</artifactId>
        </dependency>

    </dependencies>
</project>