<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jpower-core</artifactId>
        <groupId>top.jpower</groupId>
        <version>3.0.1</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jpower-core-ai</artifactId>
    <name>JPower Core AI</name>
    <packaging>jar</packaging>
    <description>
        JPower AI智能调用模块
    </description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-util</artifactId>
            <version>${top.jpower.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-autoconfigure-model-chat-client</artifactId>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-dbs</artifactId>
            <version>${top.jpower.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-nacos</artifactId>
            <version>${top.jpower.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>top.jpower</groupId>
            <artifactId>jpower-core-nacos</artifactId>
            <version>${top.jpower.version}</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

</project>