server:
  port: 80

spring:
  profiles:
    active: dev
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#日志打印级别
logging:
  level:
    root: info

jpower:
  tenant:
    #    是否启用多租户模式
    enable: false
  dev:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 12345678
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      database: 0
  #   测试环境
  test:
    #测试环境是否需要登陆（只有Boot项目会生效）
    is-login: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.8:18995/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: Wlcb@20200515
    redis:
      host: 192.168.128.104
      password: Wlcb20200515
      port: 6379
      database: 99
  #  正式环境
  prod:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.3.189.156:18992/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: root
    redis:
      host: 192.168.128.100
      password: Wlcb20200515
      port: 6379
      database: 99