server:
  port: 80

spring:
  profiles:
    active: dev
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#日志打印级别
logging:
  level:
    root: info

jpower:
#  xss:
#    #是否开启富文本过滤(如果开启，content参数名和以WithHtml结尾得参数名将不进行XSS过滤，默认关闭)
#    isIncludeRichText: false
#    #XSS不过滤得接口路径，支持通配符模式
#    excludes:
#      - /core/**
#  auth:
#    client:
#    #开启需要校验的客户端，值写数据库的clientCode即可
#      - code: admin
#    #需要客户端校验的URL
#        path:
#          - /core/user/**
#    #鉴权需要过滤的白名单地址
#    whileIp:
#      - 192.168.1.2
##      - 0:0:0:0:0:0:0:1
  dev:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      database: 0
  #   测试环境
  test:
    #测试环境是否需要登陆（只有Boot项目会生效）
    is-login: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://219.148.186.214:18995/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: Wlcb@20200515
    redis:
      host: 192.168.128.104
      password: Wlcb20200515
      port: 6379
      database: 99
  #  正式环境
  prod:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.3.189.156:18992/jpower?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: root
    redis:
      host: 192.168.128.100
      password: Wlcb20200515
      port: 6379
      database: 99