version: '3'
services:
  nginx:
    image: nginx:stable-alpine-perl
    hostname: "jpower-nginx"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 81:81
    volumes:
      - /docker/nginx/jpower/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.90

  skywalking-oap:
    image: apache/skywalking-oap-server:8.9.1
    privileged: true
    restart: always
    volumes:
      - /docker/skywalking/mysql-connector-java-5.1.47.jar:/skywalking/oap-libs/mysql-connector-java-5.1.47.jar
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://192.169.0.8:3306/sky_walking?rewriteBatchedStatements=true
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: 12345678
      TZ: Asia/Shanghai
    networks:
      - jpower_net

  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    privileged: true
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 83:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
      TZ: Asia/Shanghai
    networks:
      - jpower_net

  nacos:
    image: "nacos/nacos-server:v2.0.4"
    hostname: "nacos-standalone"
    privileged: true
    depends_on:
      - sentinel
    links:
      - sentinel
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
#      如不需要数据库做数据持久化配置删掉下面得环境变量即可
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.128.97
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=Wlcb@20200515
    volumes:
      - /docker/nacos/standalone-logs/:/home/nacos/logs
      - /docker/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 82:8848
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.50

  sentinel:
    image: "jpowerplus/sentinel-dashboard:1.8.3"
    hostname: "sentinel-standalone"
    privileged: true
    volumes:
      - /docker/sentinel/logs/:/root/logs/csp/
    ports:
      - 84:8858
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.51

  seata:
    image: seataio/seata-server:1.4.2
    privileged: true
    hostname: seata-server
    ports:
      - 85:8091
    volumes:
      - /docker/seata/logs/:/root/logs/seata/
# 使用自定义配置文件放开
#      - /docker/seata/config/:/jpower/seata-config
    environment:
      - SEATA_PORT=8091
# 使用自定义配置文件放开，并编写好配置放到下面的目录中
#      - SEATA_CONFIG_NAME=file:/jpower/seata-config/registry
    expose:
      - 8091
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.54

  jpower-admin:
    image: "219.148.186.235:99/jpower/admin-server:2.1.1"
    privileged: true
    restart: always
    ports:
      - 86:8868
    networks:
      - jpower_net

  jpower-gateway:
    image: "219.148.186.235:99/jpower/gateway-server:2.1.1"
    privileged: true
    volumes:
#      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    restart: always
    networks:
      jpower_net:
        ipv4_address: 172.16.238.25

  jpower-auth:
    image: "219.148.186.235:99/jpower/auth-server:2.1.1"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    restart: always
    networks:
      - jpower_net

  jpower-user:
    image: "219.148.186.235:99/jpower/user-server:2.1.1"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    restart: always
    networks:
      - jpower_net

  jpower-system:
    image: "219.148.186.235:99/jpower/system-server:2.1.1"
    privileged: true
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    restart: always
    networks:
      - jpower_net

  jpower-file:
    image: "219.148.186.235:99/jpower/file-server:2.1.1"
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
#      系统文件映射路径
      - /docker/file/:/root/file
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    privileged: true
    restart: always
    networks:
      - jpower_net

  jpower-api:
    image: "219.148.186.235:99/jpower/api-server:2.1.1"
    volumes:
      #      系统文件映射路径
      - /docker/api/:/root/file
    ports:
      - 18000:18000
    privileged: true
    restart: always
    networks:
      - jpower_net

  jpower-log:
    image: "219.148.186.235:99/jpower/log-server:2.1.1"
    volumes:
      #      skywalking指针得目录，需要映射到容器，如果skywalking指针得目录在宿主机上得位置改变了这里也需要修改
      - /docker/skywalking/agent/:/jpower/skywalking/agent/
      #      系统文件映射路径
      - /docker/log/:/root/file
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/jpower/skywalking/agent/skywalking-agent.jar
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800
    privileged: true
    restart: always
    networks:
      - jpower_net

networks:
  jpower_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24