;
; cdr_odbc.conf
;

[global]
dsn=asterisk
;loguniqueid=yes
;dispositionstring=yes
;table=cdr		;"cdr" is default table name
;usegmtime=no             ; set to "yes" to log in GMT
;hrtime=yes		;Enables microsecond accuracy with the billsec and duration fields
;newcdrcolumns=yes ; Enable logging of post-1.8 CDR columns (peeraccount, linkedid, sequence)

[asterisk] ; 这里是对应cdr表的配置段
table = cdr ; 你的CDR表名
