[inbound-dialer]
exten = _X.,1,Verbose(1, "呼入 PSTN: ${EXTEN}")    
same = n,AGI(agi://{{AGI_HOST}}/call.agi?type=1)   ; 地址要改成IVR程序地址,IVR必须和asterisk部署到一台服务器
same = n,Hangup()

[outbound-dialer]
; 机器人外呼
exten = robot,1,Verbose(1, "呼出 PSTN: ${EXTEN}")
same = n,AGI(agi://{{AGI_HOST}}/call.agi?type=2)  ; 地址要改成IVR程序地址,IVR必须和asterisk部署到一台服务器
same = n,Hangup()


exten = _X.,1,Verbose(1, "外拨 PSTN: ${EXTEN}")
same = n,AGI(agi://{{AGI_HOST}}/callout.agi)
same = n,Hangup()

