;[global]
;type=global
;endpoint_identifier_order=auth_username,ip,username

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
; 如果是云服务器请把这里的配置也加上，本地网络环境可以去掉 start
; 以下两项由 entrypoint.sh 根据环境变量 EXTERNAL_ADDRESS 动态启用
;{{EXTERNAL_ADDRESS}}
; 如果是云服务器请把这里的配置也加上，本地网络环境可以去掉 end
allow_reload=yes
